
export default class ActionTypes {

    static SELECT_FIRST_CURRENCY = 'SELECT_FIRST_CURRENCY';
    static SELECT_SECOND_CURRENCY = 'SELECT_SECOND_CURRENCY';
    static UPDATE_EXCHANGE_AMOUNT = 'UPDATE_EXCHANGE_AMOUNT';
    static FOCUS_ON_CURRENCY = 'FOCUS_ON_CURRENCY';
    static UPDATE_RATES = 'UPDATE_RATES';

    static SET_AMOUNTS = 'SET_AMOUNTS';

    static EXCHANGE = 'EXCHANGE';

}
